resilience4j:
    circuitbreaker:
      instances:
        orderService:
          registerhealthIndicator: true
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateThreshold: 50
          minimumNumberOfCalls: 5
          permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          waitDurationInOpenState: 60s
          slidingWindowType: COUNT_BASED

