resilience4j:
    circuitbreaker:
    instances:
      orderService:
        registerhealthIndicator: true
          automaticTransitionFromOpenToHalfOpenEnabled: true
          failureRateTreshold: 50
          minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
          slidingWindowSize: 10
          waitDurationInOpenState: 5s
          slidingWindowType: COUNT_BASED


management:
  health:
    circuitbreakers:
      enabled: true